CREATE TABLE IF NOT EXISTS `job_brief_table` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `unique_id` varchar(50) NOT NULL COMMENT 'Transporter TMID',
  `job_id` varchar(50) NOT NULL COMMENT 'Job ID from jobs table',
  `name` varchar(255) DEFAULT NULL,
  `job_location` varchar(255) DEFAULT NULL,
  `route` text DEFAULT NULL,
  `vehicle_type` varchar(100) DEFAULT NULL,
  `license_type` varchar(50) DEFAULT NULL,
  `experience` varchar(50) DEFAULT NULL,
  `salary_fixed` decimal(10,2) DEFAULT NULL,
  `salary_variable` decimal(10,2) DEFAULT NULL,
  `esi_pf` enum('Yes','No') DEFAULT 'No',
  `food_allowance` decimal(10,2) DEFAULT NULL,
  `trip_incentive` decimal(10,2) DEFAULT NULL,
  `rehne_ki_suvidha` enum('Yes','No') DEFAULT 'No',
  `mileage` varchar(50) DEFAULT NULL,
  `fast_tag_road_kharcha` enum('Company','Driver') DEFAULT 'Company',
  `call_status_feedback` varchar(100) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `unique_id` (`unique_id`),
  KEY `job_id` (`job_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
